# Generated by Django 5.1 on 2024-09-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksammlung', '0002_subkategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategorien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='links',
            name='kategorie',
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linksammlung.autor')),
            ],
        ),
        migrations.CreateModel(
            name='SubKategorien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linksammlung.kategorien')),
            ],
        ),
        migrations.CreateModel(
            name='Quelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('playlist_number', models.IntegerField()),
                ('href', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linksammlung.autor')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linksammlung.playlists')),
                ('subkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linksammlung.subkategorien')),
            ],
        ),
        migrations.DeleteModel(
            name='SubKategorie',
        ),
        migrations.DeleteModel(
            name='Kategorie',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
