# Generated by Django 5.1 on 2024-09-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksammlung', '0003_autor_kategorien_remove_links_kategorie_playlists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorien',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subkategorien',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='autor',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='autor',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='linksammlung.playlists'),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='playlist_number',
            field=models.IntegerField(default=1),
        ),
    ]
