# Generated by Django 5.1 on 2024-09-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksammlung', '0005_alter_autor_description_alter_autor_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anwendung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='xxx')),
            ],
        ),
    ]
