# Generated by Django 5.1 on 2024-09-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksammlung', '0006_anwendung'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorien',
            name='anwendung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linksammlung.anwendung'),
        ),
        migrations.AlterField(
            model_name='anwendung',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='kategorien',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linksammlung.playlists'),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='playlist_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subkategorien',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
