# Generated by Django 5.1 on 2024-09-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksammlung', '0010_alter_quelle_subkat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subkategorien',
            name='kate',
        ),
        migrations.AddField(
            model_name='quelle',
            name='kate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linksammlung.kategorien'),
        ),
    ]
