# Generated by Django 5.1 on 2024-09-16 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksammlung', '0011_remove_subkategorien_kate_quelle_kate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quelle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linksammlung.autor'),
        ),
    ]
