# Generated by Django 5.1 on 2024-09-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksammlung', '0012_alter_quelle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quelle',
            name='author',
            field=models.ForeignKey(default='none', null=True, on_delete=django.db.models.deletion.CASCADE, to='linksammlung.autor'),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='kate',
            field=models.ForeignKey(default='none', null=True, on_delete=django.db.models.deletion.CASCADE, to='linksammlung.kategorien'),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='list',
            field=models.ForeignKey(default='none', null=True, on_delete=django.db.models.deletion.CASCADE, to='linksammlung.playlists'),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='playlist_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='subkat',
            field=models.ForeignKey(default='none', null=True, on_delete=django.db.models.deletion.CASCADE, to='linksammlung.subkategorien'),
        ),
    ]
