# Generated by Django 5.1 on 2024-09-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linksammlung', '0013_alter_quelle_author_alter_quelle_kate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quelle',
            name='author',
        ),
    ]
